In [42]:
import os
import pandas as pd
from bs4 import BeautifulSoup
from io import StringIO
SCORE_DIR = "data2/scores"

In [45]:
def parse_html(box_score):
    with open(box_score) as f: 
        html = f.read()
        
    soup = BeautifulSoup(html)
    # selects the pieces that needs to be removed from the data
    # decompose = removes all the selected pieces from the html
    [s.decompose() for s in soup.select("tr.over_header")]
    [s.decompose() for s in soup.select("tr.thead")]
    
    return soup

In [46]:
def read_line_score(soup):
    # attrs = attributes, functions like selector for beautifulSoup but for pandas
    # read_html by default returns a list of data frame
    # StringIO is needed because if not pandas with lxml will interpret 
    # str(soup) as a filename/URL instead of as an html content 
    line_score = pd.read_html(StringIO(str(soup)), attrs={"id": "line_score"})[0]
    cols = list(line_score.columns)
    cols[0] = "team"
    cols[-1] = "total"
    line_score.columns = cols
    
    line_score = line_score[["team", "total"]]
    return line_score

In [47]:
def read_stats(soup, team, stat):
    
    # index_col => the player's name
    df = pd.read_html(StringIO(str(soup)), attrs={"id": f"box-{team}-game-{stat}"}, index_col=0)[0]
    # pd.to_numeric => removes the data in STRING such as DID NOT PLAY into 
    # numeric value NAN, meaning missing value, so the machine can take it for \
    # machine learning
    df = df.apply(pd.to_numeric, errors="coerce")
    return df

In [48]:
def read_season_info(soup):
    # select by default returns a list, we simply want the first element
    nav = soup.select("#bottom_nav_container")[0]
    hrefs = [a["href"] for a in nav.find_all("a")]
    season = os.path.basename(hrefs[1]).split("_")[0]
    
    return season

In [49]:
box_scores = os.listdir(SCORE_DIR)
box_scores = [os.path.join(SCORE_DIR, f) for f in box_scores if f.endswith("html")]

In [65]:
base_cols = None
games = []

for box_score in box_scores:
     
     soup = parse_html(box_score)
     print(box_score)
     line_score = read_line_score(soup)
     teams = list(line_score["team"])
     print(line_score.columns.get_loc("team"))
     summaries = []
     for team in teams:
          
          basic = read_stats(soup, team, "basic")
          advanced = read_stats(soup, team, "advanced")
          
          # Extract the total data stats for each team as for in order for machines
          # to learn/take data, the data needs to be in a single row
          # iloc method indexes data frame by position, in our case -1 means to take
          # the last row and the : means to take all rows
          total = pd.concat([basic.iloc[-1, :], advanced.iloc[-1, :]])
          total.index = total.index.str.lower()
          
          # For this it will mean to look through all rows excpet the last one
          maxes = pd.concat([basic.iloc[:-1, :].max(), advanced.iloc[:-1, :].max()])
          maxes.index = maxes.index.str.lower() + "_max"

          summary = pd.concat([total, maxes])
          
          if base_cols is None:
               # First time it loops through the loop, it will go over the html and 
               # find all the values in the box_score and determine those values 
               # to look for in other box_scores as well. Also removes any duplicate
               # value, for ex: MP(minutes played) exists in both advanced and basic
               base_cols = list(summary.index.drop_duplicates(keep="first"))
               base_cols = [b for b in base_cols if "bpm" not in b]
          
          summary = summary[base_cols]
          
          summaries.append(summary)

     summary = pd.concat(summaries, axis=1).T

     game = pd.concat([summary, line_score], axis = 1)
     
     print(f"IN game team is located at: {game.columns.get_loc("team")}")
     

     game["home"] = [0, 1]

     # Flips the data frame so the first and second row switches
     game_opp = game.iloc[::-1].reset_index()
     game_opp.columns += "_opp"

     full_game = pd.concat([game, game_opp], axis = 1)
     full_game["season"] = read_season_info(soup)
     full_game["date"] = os.path.basename(box_score)[:8]
     full_game["date"] = pd.to_datetime(full_game["date"], format = "%Y%m%d")
     full_game["won"] = full_game["total"] > full_game["total_opp"]

     print(f"IN full_game team is located at: {full_game.columns.get_loc("team")}")

     games.append(full_game)
     
     print(f"IN games team is located at: {games[0].columns.get_loc("team")}")

     if len(games) % 100 == 0:
          print(f"{len(games)} / {len(box_scores)}")

data2/scores/202211070MIA.html
0
IN game team is located at: 72
IN full_game team is located at: 72
IN games team is located at: 72
data2/scores/202212140DAL.html
0
IN game team is located at: 72
IN full_game team is located at: 72
IN games team is located at: 72
data2/scores/202212070TOR.html
0
IN game team is located at: 72
IN full_game team is located at: 72
IN games team is located at: 72
data2/scores/202501290GSW.html
0

KeyboardInterrupt:

In [73]:
games_df.columns.get_loc("team")

72

In [40]:
# Combine all the games and treat each game as rows
games_df = pd.concat(games, ignore_index=True)

In [66]:
games_df

,mp,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,38.0,72.0,0.528,16.0,37.0,0.432,18.0,21.0,...,26.2,26.8,155.0,123.0,MIA,107,1,2023,2022-11-07,True
1,240.0,240.0,40.0,84.0,0.476,14.0,39.0,0.359,13.0,15.0,...,41.0,37.3,160.0,121.0,POR,110,0,2023,2022-11-07,False
2,240.0,240.0,41.0,78.0,0.526,8.0,24.0,0.333,15.0,19.0,...,28.6,41.1,250.0,125.0,DAL,90,1,2023,2022-12-14,True
3,240.0,240.0,29.0,74.0,0.392,13.0,38.0,0.342,19.0,26.0,...,12.6,33.0,183.0,110.0,CLE,105,0,2023,2022-12-14,False
4,240.0,240.0,37.0,87.0,0.425,7.0,33.0,0.212,32.0,35.0,...,20.0,32.3,226.0,117.0,TOR,126,1,2023,2022-12-07,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17647,240.0,240.0,33.0,85.0,0.388,12.0,44.0,0.273,28.0,34.0,...,51.5,36.2,141.0,114.0,BOS,117,0,2020,2020-09-19,False
17648,240.0,240.0,43.0,91.0,0.473,17.0,45.0,0.378,23.0,32.0,...,53.2,31.1,225.0,130.0,UTA,124,1,2025,2024-10-23,True
17649,240.0,240.0,40.0,85.0,0.471,10.0,26.0,0.385,34.0,45.0,...,22.5,34.2,258.0,125.0,MEM,126,0,2025,2024-10-23,False
17650,240.0,240.0,42.0,82.0,0.512,12.0,27.0,0.444,12.0,19.0,...,53.2,28.0,146.0,126.0,TOR,121,1,2024,2023-11-24,False
17651,240.0,240.0,44.0,83.0,0.530,13.0,39.0,0.333,20.0,27.0,...,25.0,34.3,195.0,136.0,CHI,108,0,2024,2023-11-24,True

In [59]:
games_df.to_csv("nba_games.csv")

In [9]:
box_scores

['data2/scores/202211070MIA.html',
 'data2/scores/202212140DAL.html',
 'data2/scores/202212070TOR.html',
 'data2/scores/202501290GSW.html',
 'data2/scores/202604020LAC.html',
 'data2/scores/202104300MEM.html',
 'data2/scores/202402130BRK.html',
 'data2/scores/202501280GSW.html',
 'data2/scores/202311110ATL.html',
 'data2/scores/202412110HOU.html',
 'data2/scores/202212090UTA.html',
 'data2/scores/202404110POR.html',
 'data2/scores/202201230MIN.html',
 'data2/scores/202001160NOP.html',
 'data2/scores/202203180PHO.html',
 'data2/scores/202102190ORL.html',
 'data2/scores/202411080MEM.html',
 'data2/scores/202603180IND.html',
 'data2/scores/201911180HOU.html',
 'data2/scores/202210290BRK.html',
 'data2/scores/202411200CLE.html',
 'data2/scores/202605070OKC.html',
 'data2/scores/202603110ORL.html',
 'data2/scores/202111240GSW.html',
 'data2/scores/202310280CLE.html',
 'data2/scores/202103030TOR.html',
 'data2/scores/202411080DEN.html',
 'data2/scores/202211070DET.html',
 'data2/scores/202103100DAL.html',
 'data2/scores/202412210MIL.html',
 'data2/scores/202502050OKC.html',
 'data2/scores/202103280LAL.html',
 'data2/scores/202401050PHI.html',
 'data2/scores/202501220HOU.html',
 'data2/scores/202502110PHO.html',
 'data2/scores/202602200LAL.html',
 'data2/scores/202008220POR.html',
 'data2/scores/202602210PHO.html',
 'data2/scores/202502100LAL.html',
 'data2/scores/202102120ATL.html',
 'data2/scores/202202280ORL.html',
 'data2/scores/202305060MIA.html',
 'data2/scores/202203070SAS.html',
 'data2/scores/202212060DEN.html',
 'data2/scores/202211190POR.html',
 'data2/scores/202501070CHO.html',
 'data2/scores/202503030PHI.html',
 'data2/scores/202102090SAC.html',
 'data2/scores/202212070MEM.html',
 'data2/scores/202105080PHI.html',
 'data2/scores/202211140GSW.html',
 'data2/scores/202102130ATL.html',
 'data2/scores/202504180ATL.html',
 'data2/scores/202001170DAL.html',
 'data2/scores/202601130HOU.html',
 'data2/scores/202104050SAS.html',
 'data2/scores/202104220DAL.html',
 'data2/scores/202203210DAL.html',
 'data2/scores/202403250HOU.html',
 'data2/scores/201912010TOR.html',
 'data2/scores/202204130NOP.html',
 'data2/scores/202101130MIN.html',
 'data2/scores/202204010MEM.html',
 'data2/scores/202410300PHI.html',
 'data2/scores/202412080MIA.html',
 'data2/scores/202403140MIL.html',
 'data2/scores/202411230LAL.html',
 'data2/scores/202403220POR.html',
 'data2/scores/202302260GSW.html',
 'data2/scores/202406060BOS.html',
 'data2/scores/202511210CHI.html',
 'data2/scores/202601230MIL.html',
 'data2/scores/202204010DEN.html',
 'data2/scores/202601150POR.html',
 'data2/scores/202002050DET.html',
 'data2/scores/202210290CHI.html',
 'data2/scores/202403170WAS.html',
 'data2/scores/202601190GSW.html',
 'data2/scores/202603310LAC.html',
 'data2/scores/202505090DEN.html',
 'data2/scores/202103110NOP.html',
 'data2/scores/202403230POR.html',
 'data2/scores/202304260MIL.html',
 'data2/scores/202212140ORL.html',
 'data2/scores/202201250POR.html',
 'data2/scores/202201130MIL.html',
 'data2/scores/202604180CLE.html',
 'data2/scores/202201110WAS.html',
 'data2/scores/202106100MIL.html',
 'data2/scores/202511070MIA.html',
 'data2/scores/202105100CLE.html',
 'data2/scores/202201290GSW.html',
 'data2/scores/202512070TOR.html',
 'data2/scores/202103020BOS.html',
 'data2/scores/202111100CHI.html',
 'data2/scores/202502080LAC.html',
 'data2/scores/202204010BOS.html',
 'data2/scores/202311220PHO.html',
 'data2/scores/202312110HOU.html',
 'data2/scores/202304090NYK.html',
 'data2/scores/202202100PHO.html',
 'data2/scores/202401270DAL.html',
 'data2/scores/202110200POR.html',
 'data2/scores/202301040PHI.html',
 'data2/scores/202502230ATL.html',
 'data2/scores/202105130PHO.html',
 'data2/scores/202312160POR.html',
 'data2/scores/202510290BRK.html',
 'data2/scores/202002220CHI.html',
 'data2/scores/202311080MEM.html',
 'data2/scores/202001060SAC.html',
 'data2/scores/202211200BRK.html',
 'data2/scores/202102200LAL.html',
 'data2/scores/202303010CHO.html',
 'data2/scores/201912020SAC.html',
 'data2/scores/202002230CHI.html',
 'data2/scores/202603030TOR.html',
 'data2/scores/202312210MIL.html',
 'data2/scores/201912190ATL.html',
 'data2/scores/202312170POR.html',
 'data2/scores/202311080DEN.html',
 'data2/scores/202503190PHO.html',
 'data2/scores/202511190POR.html',
 'data2/scores/202605080PHI.html',
 'data2/scores/202302130CHI.html',
 'data2/scores/202512070MEM.html',
 'data2/scores/202203200ORL.html',
 'data2/scores/202101120HOU.html',
 'data2/scores/202210250WAS.html',
 'data2/scores/201912130ORL.html',
 'data2/scores/202204030SAC.html',
 'data2/scores/202203280IND.html',
 'data2/scores/202203020PHI.html',
 'data2/scores/202406140DAL.html',
 'data2/scores/202503190LAL.html',
 'data2/scores/202104220ORL.html',
 'data2/scores/202012260POR.html',
 'data2/scores/202603280PHO.html',
 'data2/scores/202511180POR.html',
 'data2/scores/202503210DAL.html',
 'data2/scores/202105120LAL.html',
 'data2/scores/202502200IND.html',
 'data2/scores/202411080BOS.html',
 'data2/scores/202210260MIL.html',
 'data2/scores/202103300LAC.html',
 'data2/scores/202312080MIA.html',
 'data2/scores/202101140POR.html',
 'data2/scores/202401260NOP.html',
 'data2/scores/202504130NOP.html',
 'data2/scores/202212040SAC.html',
 'data2/scores/202504010MEM.html',
 'data2/scores/202104300BOS.html',
 'data2/scores/202510290CHI.html',
 'data2/scores/202603110NOP.html',
 'data2/scores/202311220LAL.html',
 'data2/scores/202403240MIN.html',
 'data2/scores/202102230CLE.html',
 'data2/scores/202211210CHI.html',
 'data2/scores/202102190NOP.html',
 'data2/scores/202504010DEN.html',
 'data2/scores/201912010BRK.html',
 'data2/scores/202212070CHI.html',
 'data2/scores/202401150NYK.html',
 'data2/scores/202503150DET.html',
 'data2/scores/202001040BRK.html',
 'data2/scores/202402120MEM.html',
 'data2/scores/202008010IND.html',
 'data2/scores/202111030ORL.html',
 'data2/scores/202007310MIL.html',
 'data2/scores/202603220NYK.html',
 'data2/scores/201911270BOS.html',
 'data2/scores/202104300BRK.html',
 'data2/scores/202303080NOP.html',
 'data2/scores/202205070MIL.html',
 'data2/scores/202312050LAL.html',
 'data2/scores/202504210NYK.html',
 'data2/scores/202201280SAS.html',
 'data2/scores/202101060PHO.html',
 'data2/scores/202410260DET.html',
 'data2/scores/202106100UTA.html',
 'data2/scores/202111100BOS.html',
 'data2/scores/202403180SAC.html',
 'data2/scores/202211120LAC.html',
 'data2/scores/202503140MIA.html',
 'data2/scores/202101120OKC.html',
 'data2/scores/202511080CLE.html',
 'data2/scores/202305110PHI.html',
 'data2/scores/202511200MEM.html',
 'data2/scores/202302100SAC.html',
 'data2/scores/202210280DEN.html',
 'data2/scores/202302110SAC.html',
 'data2/scores/202201120UTA.html',
 'data2/scores/202101130OKC.html',
 'data2/scores/202303310PHO.html',
 'data2/scores/202112080MIN.html',
 'data2/scores/202009130DEN.html',
 'data2/scores/202111230LAC.html',
 'data2/scores/202104300CHI.html',
 'data2/scores/202510290BOS.html',
 'data2/scores/202603190CHO.html',
 'data2/scores/202504260MIA.html',
 'data2/scores/202302230PHI.html',
 'data2/scores/202001040CHI.html',
 'data2/scores/202312060CLE.html',
 'data2/scores/202101230UTA.html',
 'data2/scores/202002200SAC.html',
 'data2/scores/202512200DET.html',
 'data2/scores/202402120TOR.html',
 'data2/scores/202212070BRK.html',
 'data2/scores/202401120MIA.html',
 'data2/scores/202101070LAL.html',
 'data2/scores/202311280NYK.html',
 'data2/scores/202511140SAS.html',
 'data2/scores/202110260OKC.html',
 'data2/scores/202302120BOS.html',
 'data2/scores/202604050GSW.html',
 'data2/scores/202003020CLE.html',
 'data2/scores/202401120DET.html',
 'data2/scores/202504270DET.html',
 'data2/scores/202502050MIN.html',
 'data2/scores/202210280TOR.html',
 'data2/scores/202210260UTA.html',
 'data2/scores/202511210TOR.html',
 'data2/scores/202603250DET.html',
 'data2/scores/202110270OKC.html',
 'data2/scores/202604100NYK.html',
 'data2/scores/202312110OKC.html',
 'data2/scores/202304290DEN.html',
 'data2/scores/202112110MIA.html',
 'data2/scores/202111020DAL.html',
 'data2/scores/201912260DET.html',
 'data2/scores/202104160DET.html',
 'data2/scores/202103230NYK.html',
 'data2/scores/202512070CHI.html',
 'data2/scores/202111240SAS.html',
 'data2/scores/202405210BOS.html',
 'data2/scores/202601040CLE.html',
 'data2/scores/202110280PHI.html',
 'data2/scores/202008080DAL.html',
 'data2/scores/202602040MIL.html',
 'data2/scores/202505290NYK.html',
 'data2/scores/202001220DET.html',
 'data2/scores/201911270TOR.html',
 'data2/scores/202511120LAC.html',
 'data2/scores/202504010CHI.html',
 'data2/scores/202303030ATL.html',
 'data2/scores/201912270MIA.html',
 'data2/scores/202510290DEN.html',
 'data2/scores/202001220MIA.html',
 'data2/scores/202203280CHO.html',
 'data2/scores/202501120UTA.html',
 'data2/scores/202601130OKC.html',
 'data2/scores/202203150MIA.html',
 'data2/scores/202603030CHI.html',
 'data2/scores/202002230TOR.html',
 'data2/scores/202311080BRK.html',
 'data2/scores/202501290SAS.html',
 'data2/scores/202601190SAS.html',
 'data2/scores/202204260MIA.html',
 'data2/scores/202511210BOS.html',
 'data2/scores/202402230PHI.html',
 'data2/scores/202112030GSW.html',
 'data2/scores/202512060BRK.html',
 'data2/scores/202111100DEN.html',
 'data2/scores/202501230OKC.html',
 'data2/scores/202411070MIL.html',
 'data2/scores/202602110CHO.html',
 'data2/scores/202103250MIA.html',
 'data2/scores/202601220UTA.html',
 'data2/scores/202402080IND.html',
 'data2/scores/202403150UTA.html',
 'data2/scores/202402220PHI.html',
 'data2/scores/202302120TOR.html',
 'data2/scores/202002080PHO.html',
 'data2/scores/202303090ORL.html',
 'data2/scores/202301120MIA.html',
 'data2/scores/202404030PHO.html',
 'data2/scores/202008090NOP.html',
 'data2/scores/202111100MEM.html',
 'data2/scores/202210280BOS.html',
 'data2/scores/202411040WAS.html',
 'data2/scores/202212200DET.html',
 'data2/scores/202501220OKC.html',
 'data2/scores/202412100OKC.html',
 'data2/scores/202002230DEN.html',
 'data2/scores/202311080CHI.html',
 'data2/scores/201912210NYK.html',
 'data2/scores/202212200MIA.html',
 'data2/scores/202104110NYK.html',
 'data2/scores/201911270MEM.html',
 'data2/scores/202001240NYK.html',
 'data2/scores/201911260DEN.html',
 'data2/scores/202510270UTA.html',
 'data2/scores/202510290TOR.html',
 'data2/scores/202404290DEN.html',
 'data2/scores/202301130DET.html',
 'data2/scores/202502030POR.html',
 'data2/scores/202511110PHI.html',
 'data2/scores/202112080HOU.html',
 'data2/scores/202008240OKC.html',
 'data2/scores/202501040DET.html',
 'data2/scores/202008030MIA.html',
 'data2/scores/202302140POR.html',
 'data2/scores/202301180NOP.html',
 'data2/scores/202112230LAL.html',
 'data2/scores/202411020SAS.html',
 'data2/scores/202112080TOR.html',
 'data2/scores/202311060PHI.html',
 'data2/scores/202512210ATL.html',
 'data2/scores/202102070LAC.html',
 'data2/scores/202403050NYK.html',
 'data2/scores/202311240ORL.html',
 'data2/scores/202403290WAS.html',
 'data2/scores/202211200HOU.html',
 'data2/scores/202001280DAL.html',
 'data2/scores/202301210PHO.html',
 'data2/scores/202210280MIN.html',
 'data2/scores/202401120ATL.html',
 'data2/scores/202502050TOR.html',
 'data2/scores/202202160ORL.html',
 'data2/scores/202510230GSW.html',
 'data2/scores/202211130WAS.html',
 'data2/scores/202401130ATL.html',
 'data2/scores/202502040TOR.html',
 'data2/scores/201912300UTA.html',
 'data2/scores/202501040MIA.html',
 'data2/scores/202211120WAS.html',
 'data2/scores/202110270BRK.html',
 'data2/scores/202212100CLE.html',
 'data2/scores/202204010OKC.html',
 'data2/scores/202412280POR.html',
 'data2/scores/202401190ORL.html',
 'data2/scores/202102270ORL.html',
 'data2/scores/202403020MIA.html',
 'data2/scores/202601080CHO.html',
 'data2/scores/202111200MIL.html',
 'data2/scores/202112080MEM.html',
 'data2/scores/202111220WAS.html',
 'data2/scores/202001100PHO.html',
 'data2/scores/202602270DAL.html',
 'data2/scores/202401100IND.html',
 'data2/scores/202102040PHI.html',
 'data2/scores/202503140ATL.html',
 'data2/scores/201911270HOU.html',
 'data2/scores/201912140PHO.html',
 'data2/scores/202603270IND.html',
 'data2/scores/202112090MEM.html',
 'data2/scores/202205060PHI.html',
 'data2/scores/202203270PHO.html',
 'data2/scores/202111170POR.html',
 'data2/scores/202103160LAL.html',
 'data2/scores/202412250GSW.html',
 'data2/scores/202602260DAL.html',
 'data2/scores/202602010SAS.html',
 'data2/scores/202301180DAL.html',
 'data2/scores/202301200LAL.html',
 'data2/scores/202111100HOU.html',
 'data2/scores/202112230PHO.html',
 'data2/scores/202101120BRK.html',
 'data2/scores/202512230IND.html',
 'data2/scores/202211050CHO.html',
 'data2/scores/202002250POR.html',
 'data2/scores/202002110WAS.html',
 'data2/scores/202212130LAL.html',
 'data2/scores/202411080OKC.html',
 'data2/scores/202502050DEN.html',
 'data2/scores/202511210HOU.html',
 'data2/scores/202410310UTA.html',
 'data2/scores/202212210ATL.html',
 'data2/scores/202303280WAS.html',
 'data2/scores/201911180BRK.html',
 'data2/scores/202101270GSW.html',
 'data2/scores/202112130IND.html',
 'data2/scores/202603150CLE.html',
 'data2/scores/202501220BRK.html',
 'data2/scores/202303110GSW.html',
 'data2/scores/202310250IND.html',
 'data2/scores/202401190NOP.html',
 'data2/scores/202402150POR.html',
 'data2/scores/202604010UTA.html',
 'data2/scores/202301090SAC.html',
 'data2/scores/202105060TOR.html',
 'data2/scores/202210230GSW.html',
 'data2/scores/202402120HOU.html',
 'data2/scores/202401210PHO.html',
 'data2/scores/202403250CHI.html',
 'data2/scores/202503020UTA.html',
 'data2/scores/202105140DAL.html',
 'data2/scores/202211210MIN.html',
 'data2/scores/202511260POR.html',
 'data2/scores/202202040TOR.html',
 'data2/scores/202105080UTA.html',
 'data2/scores/202503030UTA.html',
 'data2/scores/202510290MIN.html',
 'data2/scores/202604250PHO.html',
 'data2/scores/202401210LAL.html',
 'data2/scores/202210300DET.html',
 'data2/scores/202411040LAC.html',
 'data2/scores/202205240DAL.html',
 'data2/scores/202603080SAS.html',
 'data2/scores/202312280POR.html',
 'data2/scores/202503260PHO.html',
 'data2/scores/202404170CHI.html',
 'data2/scores/202001220ATL.html',
 'data2/scores/201911180CHI.html',
 'data2/scores/202102010SAS.html',
 'data2/scores/202203140ATL.html',
 'data2/scores/202101090CHO.html',
 'data2/scores/202303030MIA.html',
 'data2/scores/201912270ATL.html',
 'data2/scores/202602260ORL.html',
 'data2/scores/202312290POR.html',
 'data2/scores/202202170NOP.html',
 'data2/scores/202202040DEN.html',
 'data2/scores/202112100ATL.html',
 'data2/scores/202212090PHI.html',
 'data2/scores/202310270ATL.html',
 'data2/scores/202304190MIL.html',
 'data2/scores/202311080OKC.html',
 'data2/scores/202304230GSW.html',
 'data2/scores/202003060NOP.html',
 'data2/scores/202211040IND.html',
 'data2/scores/202210190UTA.html',
 'data2/scores/202201230DEN.html',
 'data2/scores/202304160DEN.html',
 'data2/scores/202304050NOP.html',
 'data2/scores/202511110UTA.html',
 'data2/scores/202412080ATL.html',
 'data2/scores/201912010MIN.html',
 'data2/scores/202311080HOU.html',
 'data2/scores/202202250NYK.html',
 'data2/scores/202510270PHI.html',
 'data2/scores/202511100UTA.html',
 'data2/scores/202304160MEM.html',
 'data2/scores/202105260NYK.html',
 'data2/scores/202304040NOP.html',
 'data2/scores/202512230CHO.html',
 'data2/scores/202411080MIN.html',
 'data2/scores/202205100MIA.html',
 'data2/scores/202404140SAC.html',
 'data2/scores/202402220UTA.html',
 'data2/scores/202312110MEM.html',
 'data2/scores/202101270SAS.html',
 'data2/scores/202303240TOR.html',
 'data2/scores/202502040CHI.html',
 'data2/scores/202401100CHO.html',
 'data2/scores/202303100SAS.html',
 'data2/scores/202601220PHI.html',
 'data2/scores/202603260CHO.html',
 'data2/scores/202201080PHO.html',
 'data2/scores/202008170LAC.html',
 'data2/scores/202101010DAL.html',
 'data2/scores/202510240LAC.html',
 'data2/scores/202201090LAL.html',
 'data2/scores/202402060PHO.html',
 'data2/scores/202403260SAC.html',
 'data2/scores/202212070MIN.html',
 'data2/scores/201911030IND.html',
 'data2/scores/202311100DET.html',
 'data2/scores/202201230TOR.html',
 'data2/scores/202002070IND.html',
 'data2/scores/202304050DAL.html',
 'data2/scores/202512190NYK.html',
 'data2/scores/202201170SAS.html',
 'data2/scores/202601110SAC.html',
 'data2/scores/202604140CHO.html',
 'data2/scores/202003060DAL.html',
 'data2/scores/202504060POR.html',
 'data2/scores/202402050CLE.html',
 'data2/scores/202110270TOR.html',
 'data2/scores/202102150NYK.html',
 'data2/scores/202312020DAL.html',
 'data2/scores/202403170LAC.html',
 'data2/scores/202502040BRK.html',
 'data2/scores/202401060WAS.html',
 'data2/scores/202604290DET.html',
 'data2/scores/202303240MEM.html',
 'data2/scores/202211070ATL.html',
 'data2/scores/202412200PHI.html',
 'data2/scores/202502050BRK.html',
 'data2/scores/202303250DEN.html',
 'data2/scores/202505080MIN.html',
 'data2/scores/202009060LAL.html',
 'data2/scores/202103030MIN.html',
 'data2/scores/202404050NOP.html',
 'data2/scores/202501230DEN.html',
 'data2/scores/202604300MIN.html',
 'data2/scores/202502080WAS.html',
 'data2/scores/202104030WAS.html',
 'data2/scores/202501220MEM.html',
 'data2/scores/202303240BOS.html',
 'data2/scores/202203020MIL.html',
 'data2/scores/201911190MEM.html',
 'data2/scores/202111040PHO.html',
 'data2/scores/202110240SAC.html',
 'data2/scores/202206100BOS.html',
 'data2/scores/202201110LAC.html',
 'data2/scores/202501310NOP.html',
 'data2/scores/202203010WAS.html',
 'data2/scores/201912060POR.html',
 'data2/scores/202511050IND.html',
 'data2/scores/202106120LAC.html',
 'data2/scores/202411170NYK.html',
 'data2/scores/202501090PHO.html',
 'data2/scores/202008250DEN.html',
 'data2/scores/202101090IND.html',
 'data2/scores/202403110SAS.html',
 'data2/scores/202311080MIN.html',
 'data2/scores/202002230OKC.html',
 'data2/scores/202312230LAC.html',
 'data2/scores/202403250TOR.html',
 'data2/scores/202101220PHI.html',
 'data2/scores/202105070CHI.html',
 'data2/scores/202601120TOR.html',
 'data2/scores/202601010DAL.html',
 'data2/scores/202204190MIA.html',
 'data2/scores/202103260CHO.html',
 'data2/scores/202302070LAL.html',
 'data2/scores/202310300MIL.html',
 'data2/scores/202302230UTA.html',
 'data2/scores/202304150SAC.html',
 'data2/scores/202112060MIL.html',
 'data2/scores/202411100DET.html',
 'data2/scores/202103030HOU.html',
 'data2/scores/202001200CHO.html',
 'data2/scores/202304040ORL.html',
 'data2/scores/202404040DAL.html',
 'data2/scores/202203160CHO.html',
 'data2/scores/202201120PHI.html',
 'data2/scores/202110270BOS.html',
 'data2/scores/202101110SAC.html',
 'data2/scores/202002120UTA.html',
 'data2/scores/202201300ORL.html',
 'data2/scores/202104140CHO.html',
 'data2/scores/202302130OKC.html',
 'data2/scores/202512060MIN.html',
 'data2/scores/201911180TOR.html',
 'data2/scores/202303270SAC.html',
 'data2/scores/202104280MIA.html',
 'data2/scores/202002290SAS.html',
 'data2/scores/202501170SAS.html',
 'data2/scores/202204010HOU.html',
 'data2/scores/202404050DAL.html',
 'data2/scores/202111040LAL.html',
 'data2/scores/202310250CHO.html',
 'data2/scores/201912180DET.html',
 'data2/scores/202211210OKC.html',
 'data2/scores/202505160NYK.html',
 'data2/scores/202505020GSW.html',
 'data2/scores/202103300WAS.html',
 'data2/scores/202312200PHI.html',
 'data2/scores/202511070ATL.html',
 'data2/scores/202510280OKC.html',
 'data2/scores/202603030MIN.html',
 'data2/scores/202412030DAL.html',
 'data2/scores/202403250DEN.html',
 'data2/scores/202103040POR.html',
 'data2/scores/202008110SAS.html',
 'data2/scores/202104290DET.html',
 'data2/scores/202101200LAC.html',
 'data2/scores/202103130CHO.html',
 'data2/scores/202104050HOU.html',
 'data2/scores/202403250SAS.html',
 'data2/scores/202204100CHO.html',
 'data2/scores/202203060HOU.html',
 'data2/scores/202601280UTA.html',
 'data2/scores/202008110MEM.html',
 'data2/scores/202402020IND.html',
 'data2/scores/202112080GSW.html',
 'data2/scores/202008030NOP.html',
 'data2/scores/202104040HOU.html',

In [58]:
advanced

,MP,TS%,eFG%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,ORtg,DRtg,BPM
Starters,,,,,,,,,,,,,,,,
Kyle Lowry,NaN,0.889,0.875,0.750,0.125,0.0,31.2,14.0,33.4,0.0,0.0,26.2,15.7,135.0,123.0,2.8
Caleb Martin,NaN,0.455,0.455,0.455,0.000,10.9,8.9,10.0,4.2,1.5,0.0,0.0,15.1,107.0,121.0,-6.1
Bam Adebayo,NaN,0.554,0.571,0.000,0.071,7.6,13.9,10.4,15.1,1.5,4.1,6.5,22.1,112.0,118.0,-1.4
Jimmy Butler,NaN,0.481,0.357,0.071,0.429,0.0,18.6,8.4,30.8,9.2,0.0,10.7,26.8,104.0,102.0,4.4
Max Strus,NaN,0.800,0.800,0.800,0.000,0.0,0.0,0.0,13.3,2.0,0.0,0.0,18.9,148.0,120.0,5.3
Gabe Vincent,NaN,0.524,0.500,0.692,0.231,0.0,4.4,2.0,12.2,2.9,3.9,17.3,23.3,89.0,116.0,-5.2
Duncan Robinson,NaN,0.500,0.500,1.000,0.000,0.0,21.7,9.8,14.4,0.0,0.0,10.0,16.7,96.0,123.0,-6.0
Dewayne Dedmon,NaN,0.740,0.600,0.200,0.800,0.0,63.6,28.6,10.9,0.0,0.0,0.0,22.1,155.0,120.0,7.2
Haywood Highsmith,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Nikola Jović,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dru Smith,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Team Totals,240.0,0.591,0.560,0.464,0.179,13.2,87.1,46.4,70.0,11.5,5.7,11.7,100.0,112.3,115.5,NaN

In [66]:
total

mp      240.000
fg       40.000
fga      84.000
fg%       0.476
3p       14.000
3pa      39.000
3p%       0.359
ft       13.000
fta      15.000
ft%       0.867
orb       5.000
drb      27.000
trb      32.000
ast      28.000
stl      11.000
blk       2.000
tov      12.000
pf       18.000
pts     107.000
gmsc        NaN
+/-         NaN
mp      240.000
ts%       0.591
efg%      0.560
3par      0.464
ftr       0.179
orb%     13.200
drb%     87.100
trb%     46.400
ast%     70.000
stl%     11.500
blk%      5.700
tov%     11.700
usg%    100.000
ortg    112.300
drtg    115.500
bpm         NaN
Name: Team Totals, dtype: float64

In [67]:
maxes

mp_max          NaN
fg_max        8.000
fga_max      14.000
fg%_max       0.625
3p_max        4.000
3pa_max       9.000
3p%_max       0.667
ft_max        6.000
fta_max       6.000
ft%_max       1.000
orb_max       3.000
drb_max       7.000
trb_max       7.000
ast_max       8.000
stl_max       6.000
blk_max       1.000
tov_max       3.000
pf_max        5.000
pts_max      16.000
gmsc_max     17.100
+/-_max       2.000
mp_max          NaN
ts%_max       0.889
efg%_max      0.875
3par_max      1.000
ftr_max       0.800
orb%_max     10.900
drb%_max     63.600
trb%_max     28.600
ast%_max     33.400
stl%_max      9.200
blk%_max      4.100
tov%_max     26.200
usg%_max     26.800
ortg_max    155.000
drtg_max    123.000
bpm_max       7.200
dtype: float64

In [77]:
summary

,mp,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,orb%_max,drb%_max,trb%_max,ast%_max,stl%_max,blk%_max,tov%_max,usg%_max,ortg_max,drtg_max
0,240.0,240.0,38.0,72.0,0.528,16.0,37.0,0.432,18.0,21.0,...,12.9,44.1,26.7,30.6,3.9,8.1,41.0,37.3,160.0,121.0
1,240.0,240.0,40.0,84.0,0.476,14.0,39.0,0.359,13.0,15.0,...,10.9,63.6,28.6,33.4,9.2,4.1,26.2,26.8,155.0,123.0

In [55]:
games_df

,mp,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,38.0,72.0,0.528,16.0,37.0,0.432,18.0,21.0,...,26.2,26.8,155.0,123.0,MIA,107,1,2023,2022-11-07,True
1,240.0,240.0,40.0,84.0,0.476,14.0,39.0,0.359,13.0,15.0,...,41.0,37.3,160.0,121.0,POR,110,0,2023,2022-11-07,False
2,240.0,240.0,41.0,78.0,0.526,8.0,24.0,0.333,15.0,19.0,...,28.6,41.1,250.0,125.0,DAL,90,1,2023,2022-12-14,True
3,240.0,240.0,29.0,74.0,0.392,13.0,38.0,0.342,19.0,26.0,...,12.6,33.0,183.0,110.0,CLE,105,0,2023,2022-12-14,False
4,240.0,240.0,37.0,87.0,0.425,7.0,33.0,0.212,32.0,35.0,...,20.0,32.3,226.0,117.0,TOR,126,1,2023,2022-12-07,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17647,240.0,240.0,33.0,85.0,0.388,12.0,44.0,0.273,28.0,34.0,...,51.5,36.2,141.0,114.0,BOS,117,0,2020,2020-09-19,False
17648,240.0,240.0,43.0,91.0,0.473,17.0,45.0,0.378,23.0,32.0,...,53.2,31.1,225.0,130.0,UTA,124,1,2025,2024-10-23,True
17649,240.0,240.0,40.0,85.0,0.471,10.0,26.0,0.385,34.0,45.0,...,22.5,34.2,258.0,125.0,MEM,126,0,2025,2024-10-23,False
17650,240.0,240.0,42.0,82.0,0.512,12.0,27.0,0.444,12.0,19.0,...,53.2,28.0,146.0,126.0,TOR,121,1,2024,2023-11-24,False
17651,240.0,240.0,44.0,83.0,0.530,13.0,39.0,0.333,20.0,27.0,...,25.0,34.3,195.0,136.0,CHI,108,0,2024,2023-11-24,True

In [113]:
game_opp

,mp_opp,mp_opp,fg_opp,fga_opp,fg%_opp,3p_opp,3pa_opp,3p%_opp,ft_opp,fta_opp,...,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp
1,240.0,240.0,40.0,84.0,0.476,14.0,39.0,0.359,13.0,15.0,...,33.4,9.2,4.1,26.2,26.8,155.0,123.0,MIA,107,1
0,240.0,240.0,38.0,72.0,0.528,16.0,37.0,0.432,18.0,21.0,...,30.6,3.9,8.1,41.0,37.3,160.0,121.0,POR,110,0

In [38]:
full_game

,mp,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,42.0,82.0,0.512,12.0,27.0,0.444,12.0,19.0,...,53.2,28.0,146.0,126.0,TOR,121,1,2024,2023-11-24,False
1,240.0,240.0,44.0,83.0,0.530,13.0,39.0,0.333,20.0,27.0,...,25.0,34.3,195.0,136.0,CHI,108,0,2024,2023-11-24,True

In [39]:
games_df = pd.concat(games, ignore_index=)

[      mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  38.0  72.0  0.528  16.0  37.0  0.432  18.0  21.0  ...
 1  240.0  240.0  40.0  84.0  0.476  14.0  39.0  0.359  13.0  15.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          26.2          26.8         155.0         123.0       MIA
 1          41.0          37.3         160.0         121.0       POR

    total_opp  home_opp  season       date    won
 0        107         1    2023 2022-11-07   True
 1        110         0    2023 2022-11-07  False

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  41.0  78.0  0.526   8.0  24.0  0.333  15.0  19.0  ...
 1  240.0  240.0  29.0  74.0  0.392  13.0  38.0  0.342  19.0  26.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          28.6          41.1         250.0         125.0       DAL
 1          12.6          33.0         183.0         110.0       CLE

    total_opp  home_opp  season       date    won
 0         90         1    2023 2022-12-14   True
 1        105         0    2023 2022-12-14  False

 [2 rows x 154 columns],
       mp     mp    fg    fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  37.0   87.0  0.425   7.0  33.0  0.212  32.0  35.0  ...
 1  240.0  240.0  47.0  106.0  0.443  12.0  43.0  0.279  20.0  24.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          20.0          32.3         226.0         117.0       TOR
 1          25.8          30.7         168.0         127.0       LAL

    total_opp  home_opp  season       date    won
 0        126         1    2023 2022-12-07  False
 1        113         0    2023 2022-12-07   True

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  40.0  99.0  0.404   9.0  39.0  0.231  20.0  25.0  ...
 1  240.0  240.0  40.0  81.0  0.494  13.0  38.0  0.342  23.0  28.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0         100.0          25.9         174.0         118.0       GSW
 1         100.0          40.8         145.0         123.0       OKC

    total_opp  home_opp  season       date    won
 0        116         1    2025 2025-01-29  False
 1        109         0    2025 2025-01-29   True

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  47.0  88.0  0.534  12.0  31.0  0.387  12.0  14.0  ...
 1  240.0  240.0  40.0  93.0  0.430   5.0  27.0  0.185  14.0  18.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0         100.0          28.6         155.0         128.0       LAC
 1          50.0          27.7         198.0         109.0       SAS

    total_opp  home_opp  season       date    won
 0         99         1    2026 2026-04-02   True
 1        118         0    2026 2026-04-02  False

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  27.0  86.0  0.314   6.0  26.0  0.231  15.0  20.0  ...
 1  240.0  240.0  34.0  99.0  0.343  11.0  39.0  0.282  13.0  16.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          16.8          30.9         157.0          90.0       MEM
 1          33.9          27.2         106.0         106.0       ORL

    total_opp  home_opp  season       date    won
 0         92         1    2021 2021-04-30  False
 1         75         0    2021 2021-04-30   True

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  43.0  83.0  0.518  15.0  37.0  0.405  17.0  23.0  ...
 1  240.0  240.0  39.0  79.0  0.494  15.0  33.0  0.455  17.0  26.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          50.0          32.5         209.0         129.0       BRK
 1          25.8          36.6         236.0         122.0       BOS

    total_opp  home_opp  season       date    won
 0        110         1    2024 2024-02-13   True
 1        118         0    2024 2024-02-13  False

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  39.0  76.0  0.513   8.0  26.0  0.308  17.0  24.0  ...
 1  240.0  240.0  36.0  92.0  0.391  17.0  49.0  0.347  25.0  31.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          25.8          28.3         154.0         115.0       GSW
 1          30.7          28.6         200.0         127.0       UTA

    total_opp  home_opp  season       date    won
 0        114         1    2025 2025-01-28  False
 1        103         0    2025 2025-01-28   True

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  41.0  84.0  0.488  12.0  38.0  0.316  23.0  25.0  ...
 1  240.0  240.0  38.0  87.0  0.437  18.0  46.0  0.391  15.0  18.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          30.8          31.1         165.0         122.0       ATL
 1          22.7          23.7         170.0         121.0       MIA

    total_opp  home_opp  season       date    won
 0        109         1    2024 2023-11-11   True
 1        117         0    2024 2023-11-11  False

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%   ft   fta  ...  \
 0  240.0  240.0  37.0  84.0  0.440  12.0  38.0  0.316  4.0   9.0  ...
 1  240.0  240.0  38.0  83.0  0.458   6.0  27.0  0.222  9.0  10.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          23.9          36.5         135.0         103.0       HOU
 1          50.0          28.5         228.0         108.0       GSW

    total_opp  home_opp  season       date    won
 0         91         1    2025 2024-12-11  False
 1         90         0    2025 2024-12-11   True

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  42.0  79.0  0.532  14.0  35.0  0.400  20.0  26.0  ...
 1  240.0  240.0  39.0  90.0  0.433  13.0  44.0  0.295  17.0  24.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          20.0          33.6         245.0         125.0       UTA
 1          30.9          37.6         142.0         119.0       MIN

    total_opp  home_opp  season       date    won
 0        108         1    2023 2022-12-09   True
 1        118         0    2023 2022-12-09  False

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  36.0  77.0  0.468  12.0  35.0  0.343  16.0  20.0  ...
 1  240.0  240.0  35.0  97.0  0.361   8.0  34.0  0.235  14.0  17.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          29.7          32.8         133.0         116.0       POR
 1          50.0          31.7         171.0         112.0       GSW

    total_opp  home_opp  season       date    won
 0         92         1    2024 2024-04-11   True
 1        100         0    2024 2024-04-11  False

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  48.0  95.0  0.505  15.0  38.0  0.395  14.0  15.0  ...
 1  240.0  240.0  48.0  92.0  0.522  14.0  32.0  0.438  26.0  31.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          13.4         100.0         250.0         136.0       MIN
 1         100.0          29.5         186.0         140.0       BRK

    total_opp  home_opp  season       date    won
 0        136         1    2022 2022-01-23  False
 1        125         0    2022 2022-01-23   True

 [2 rows x 154 columns],
       mp     mp    fg    fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  265.0  265.0  46.0  100.0  0.460  15.0  39.0  0.385  25.0  32.0  ...
 1  265.0  265.0  51.0   93.0  0.548  11.0  26.0  0.423  25.0  35.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          20.7          39.9         160.0         125.0       NOP
 1          25.0          39.5         197.0         132.0       UTA

    total_opp  home_opp  season       date    won
 0        138         1    2020 2020-01-16  False
 1        132         0    2020 2020-01-16   True

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  35.0  85.0  0.412   7.0  27.0  0.259  25.0  31.0  ...
 1  240.0  240.0  47.0  84.0  0.560  11.0  25.0  0.440  24.0  26.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          25.4          36.8         186.0         116.0       PHO
 1          33.3          45.1         209.0         143.0       CHI

    total_opp  home_opp  season       date    won
 0        129         1    2022 2022-03-18  False
 1        102         0    2022 2022-03-18   True

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  46.0  97.0  0.474  19.0  42.0  0.452   9.0  15.0  ...
 1  240.0  240.0  46.0  94.0  0.489  18.0  43.0  0.419  14.0  17.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          29.1          27.7         183.0         123.0       ORL
 1          37.5          33.7         141.0         122.0       GSW

    total_opp  home_opp  season       date    won
 0        124         1    2021 2021-02-19  False
 1        120         0    2021 2021-02-19   True

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  38.0  93.0  0.409   9.0  35.0  0.257  19.0  23.0  ...
 1  240.0  240.0  46.0  97.0  0.474  14.0  43.0  0.326  22.0  25.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          30.0          45.5         163.0         105.0       MEM
 1          28.8          43.7         250.0         130.0       WAS

    total_opp  home_opp  season       date    won
 0        128         1    2025 2024-11-08  False
 1        104         0    2025 2024-11-08   True

 [2 rows x 154 columns],
       mp     mp    fg    fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  45.0  101.0  0.446  16.0  46.0  0.348  21.0  26.0  ...
 1  240.0  240.0  46.0   91.0  0.505  12.0  27.0  0.444  15.0  17.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          40.0          39.3         161.0         135.0       IND
 1          33.3          40.0         167.0         128.0       POR

    total_opp  home_opp  season       date    won
 0        119         1    2026 2026-03-18   True
 1        127         0    2026 2026-03-18  False

 [2 rows x 154 columns],
       mp     mp    fg    fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  40.0   96.0  0.417  11.0  36.0  0.306  17.0  23.0  ...
 1  240.0  240.0  47.0  100.0  0.470  17.0  45.0  0.378  21.0  26.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          31.6          38.4         162.0         109.0       HOU
 1          53.2          30.6         147.0         132.0       POR

    total_opp  home_opp  season       date    won
 0        132         1    2020 2019-11-18  False
 1        108         0    2020 2019-11-18   True

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  40.0  94.0  0.426  23.0  46.0  0.500  22.0  26.0  ...
 1  240.0  240.0  41.0  82.0  0.500  14.0  39.0  0.359  20.0  26.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          25.0          32.6         182.0         146.0       BRK
 1          20.0          28.1         161.0         130.0       IND

    total_opp  home_opp  season       date    won
 0        116         1    2023 2022-10-29   True
 1        125         0    2023 2022-10-29  False

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  39.0  92.0  0.424   8.0  31.0  0.258  14.0  22.0  ...
 1  240.0  240.0  49.0  93.0  0.527  18.0  42.0  0.429  12.0  14.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          37.5          39.9         218.0         115.0       CLE
 1          33.3          30.7         143.0         144.0       NOP

    total_opp  home_opp  season       date    won
 0        128         1    2025 2024-11-20  False
 1        100         0    2025 2024-11-20   True

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  39.0  78.0  0.500  11.0  29.0  0.379  18.0  21.0  ...
 1  240.0  240.0  45.0  81.0  0.556  14.0  36.0  0.389  21.0  26.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          25.0          35.1         200.0         124.0       OKC
 1         100.0          59.6         228.0         140.0       LAL

    total_opp  home_opp  season       date    won
 0        125         1    2026 2026-05-07  False
 1        107         0    2026 2026-05-07   True

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  44.0  89.0  0.494  17.0  44.0  0.386  17.0  26.0  ...
 1  240.0  240.0  44.0  85.0  0.518  12.0  35.0  0.343  28.0  37.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          20.5          29.3         161.0         131.0       ORL
 1          33.3          34.1         187.0         138.0       CLE

    total_opp  home_opp  season       date    won
 0        128         1    2026 2026-03-11  False
 1        122         0    2026 2026-03-11   True

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  34.0  80.0  0.425   8.0  28.0  0.286  20.0  22.0  ...
 1  240.0  240.0  42.0  80.0  0.525  15.0  38.0  0.395  17.0  24.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          37.2          30.9         187.0         105.0       GSW
 1         100.0          28.5         125.0         124.0       PHI

    total_opp  home_opp  season       date    won
 0        116         1    2022 2021-11-24  False
 1         96         0    2022 2021-11-24   True

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  48.0  98.0  0.490  15.0  38.0  0.395  14.0  17.0  ...
 1  240.0  240.0  43.0  99.0  0.434  12.0  31.0  0.387  15.0  24.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0           9.1          35.5         228.0         136.0       CLE
 1          16.7          29.5         175.0         127.0       IND

    total_opp  home_opp  season       date    won
 0        113         1    2024 2023-10-28   True
 1        125         0    2024 2023-10-28  False

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  48.0  91.0  0.527  20.0  41.0  0.488  13.0  21.0  ...
 1  240.0  240.0  34.0  77.0  0.442  12.0  36.0  0.333  25.0  30.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          50.0          33.5         147.0         141.0       TOR
 1          25.2          31.2         197.0         115.0       DET

    total_opp  home_opp  season       date    won
 0        105         1    2021 2021-03-03   True
 1        129         0    2021 2021-03-03  False

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  46.0  94.0  0.489  20.0  43.0  0.465  10.0  13.0  ...
 1  240.0  240.0  50.0  81.0  0.617  18.0  35.0  0.514  17.0  19.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          28.6          30.3         163.0         125.0       DEN
 1          33.3          27.1         148.0         141.0       MIA

    total_opp  home_opp  season       date    won
 0        135         1    2025 2024-11-08  False
 1        122         0    2025 2024-11-08   True

 [2 rows x 154 columns],
       mp     mp    fg    fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  41.0  102.0  0.402  10.0  33.0  0.303  11.0  17.0  ...
 1  240.0  240.0  39.0   93.0  0.419   9.0  33.0  0.273  25.0  33.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          25.4          30.8         135.0         114.0       DET
 1          23.1          28.6         149.0         122.0       OKC

    total_opp  home_opp  season       date    won
 0        112         1    2023 2022-11-07  False
 1        103         0    2023 2022-11-07   True

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  38.0  83.0  0.458  12.0  28.0  0.429  16.0  20.0  ...
 1  240.0  240.0  43.0  83.0  0.518  13.0  40.0  0.325  16.0  19.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          41.0          32.0         180.0         118.0       DAL
 1          26.2          81.6         177.0         136.0       SAS

    total_opp  home_opp  season       date    won
 0        115         1    2021 2021-03-10  False
 1        104         0    2021 2021-03-10   True

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  36.0  81.0  0.444  18.0  42.0  0.429  11.0  16.0  ...
 1  240.0  240.0  44.0  98.0  0.449  20.0  48.0  0.417   4.0   5.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          20.9          30.7         146.0         113.0       MIL
 1          40.0          34.7         173.0         120.0       WAS

    total_opp  home_opp  season       date    won
 0        112         1    2025 2024-12-21  False
 1        101         0    2025 2024-12-21   True

 [2 rows x 154 columns],
       mp     mp    fg    fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  33.0   70.0  0.471  14.0  36.0  0.389  29.0  33.0  ...
 1  240.0  240.0  52.0  102.0  0.510  12.0  42.0  0.286  24.0  27.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          20.0          41.2         192.0         116.0       OKC
 1          75.0          31.8         176.0         145.0       PHO

    total_opp  home_opp  season       date    won
 0        140         1    2025 2025-02-05  False
 1        109         0    2025 2025-02-05   True

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  34.0  88.0  0.386  11.0  33.0  0.333  14.0  17.0  ...
 1  240.0  240.0  34.0  82.0  0.415  11.0  40.0  0.275  17.0  23.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          34.0          27.2         126.0         106.0       LAL
 1          25.0          31.1         232.0         108.0       ORL

    total_opp  home_opp  season       date    won
 0         96         1    2021 2021-03-28  False
 1         93         0    2021 2021-03-28   True

 [2 rows x 154 columns],
       mp     mp    fg   fga    fg%    3p   3pa    3p%    ft   fta  ...  \
 0  240.0  240.0  43.0  89.0  0.483  18.0  41.0  0.439  24.0  25.0  ...
 1  240.0  240.0  33.0  81.0  0.407   6.0  23.0  0.261  20.0  27.0  ...

    tov%_max_opp  usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  \
 0          51.5          42.5         204.0         142.0       PHI
 1          25.0          28.5         177.0         104.0       NYK

    total_opp  home_opp  season       date    won
 0         92         1    2024 2024-01-05   True