In [165]:
import pandas as pd

# Creates # index for each row
df = pd.read_csv("nba_games.csv", index_col = 0)
# Sorts the data frame to ascending order 
df = df.sort_values("date")
# Since after sorting it, the index of row becomes messy, resets the row #
df = df.reset_index(drop=True)
# df.columns.get_loc("team")


df.loc[pd.isnull(df["ft%"]), "ft%"] = 0.780
df.loc[pd.isnull(df["ft%_opp"]), "ft%_opp"] = 0.780
df.loc[pd.isnull(df["ft%_max"]), "ft%_max"] = 1.000
df.loc[pd.isnull(df["ft%_max_opp"]), "ft%_max_opp"] = 1.000

df.loc[pd.isnull(df["+/-_max_opp"]), "+/-_max_opp"] = 20
df.loc[pd.isnull(df["+/-_max"]), "+/-_max"] = 20

# avergae ft% 78%
# average max_ft 89%
# average max +- 20

In [166]:
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]
# df.columns.get_loc("team")

In [167]:
def add_target(team):
    
    # Gets the value of the result of the next game as target 
    # Check the dataframe of Boston Underneath for clear understanding
    team["target"] = team["won"].shift(-1)
    return team
    
df["target"] = df.groupby("team")["won"].shift(-1)

/var/folders/yq/k72_3tsd4dv_nt6nq1zwz2g80000gn/T/ipykernel_13253/27142777.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["target"] = df.groupby("team")["won"].shift(-1)

In [168]:
df[df["team"] == "BOS"]

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
15,240.0,33.0,74.0,0.446,11.0,34.0,0.324,27.0,29.0,0.931,...,34.0,138.0,114.0,NYK,102,0,2020,2019-11-01,True,True
63,240.0,48.0,85.0,0.565,12.0,30.0,0.400,11.0,15.0,0.733,...,24.5,214.0,122.0,CLE,113,1,2020,2019-11-05,True,True
86,240.0,40.0,93.0,0.430,10.0,33.0,0.303,18.0,23.0,0.783,...,33.8,149.0,115.0,CHO,87,1,2020,2019-11-07,True,True
125,240.0,48.0,94.0,0.511,14.0,37.0,0.378,25.0,28.0,0.893,...,35.3,161.0,135.0,SAS,115,1,2020,2019-11-09,True,True
147,240.0,41.0,86.0,0.477,15.0,35.0,0.429,19.0,25.0,0.760,...,35.0,154.0,130.0,DAL,106,0,2020,2019-11-11,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17575,240.0,36.0,81.0,0.444,20.0,47.0,0.426,16.0,17.0,0.941,...,35.4,145.0,131.0,PHI,100,1,2026,2026-04-24,True,True
17590,240.0,42.0,87.0,0.483,24.0,53.0,0.453,20.0,28.0,0.714,...,44.0,227.0,149.0,PHI,96,1,2026,2026-04-26,True,False
17599,240.0,36.0,89.0,0.404,11.0,39.0,0.282,14.0,23.0,0.609,...,63.1,268.0,113.0,PHI,113,0,2026,2026-04-28,False,False
17614,240.0,36.0,86.0,0.419,12.0,41.0,0.293,9.0,16.0,0.563,...,28.4,210.0,105.0,PHI,106,1,2026,2026-04-30,False,False
17623,240.0,37.0,93.0,0.398,13.0,49.0,0.265,13.0,16.0,0.813,...,38.7,228.0,113.0,PHI,109,0,2026,2026-05-02,False,NaN

In [169]:

# if target is NAN, meaning it's the last game played for that specifc team
# from our collected data, set it to 2
df.loc[pd.isnull(df["target"]), "target"] = 2
# Converts the boolean statements, True and False into its corresponding int 
# value, 1 and 0
df["target"] = df["target"].astype(int, errors = "ignore")


# In [33]: df = pd.DataFrame({"foo": [1, 2, 3], "bar": [4, 5, 6]})
# In [34]: df["foo"][df["bar"] > 5] = 100
# In [35]: df.loc[df["bar"] > 5, "foo"] = 100

In [170]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,41.0,99.0,0.414,12.0,48.0,0.250,22.0,27.0,0.815,...,30.6,182.0,116.0,BRK,123,1,2020,2019-11-01,False,0
1,265.0,40.0,102.0,0.392,14.0,36.0,0.389,16.0,23.0,0.696,...,34.1,206.0,113.0,LAL,119,0,2020,2019-11-01,False,1
2,240.0,44.0,93.0,0.473,13.0,35.0,0.371,26.0,30.0,0.867,...,41.0,246.0,138.0,GSW,110,1,2020,2019-11-01,True,0
3,240.0,39.0,96.0,0.406,5.0,27.0,0.185,19.0,21.0,0.905,...,28.6,123.0,106.0,CLE,95,0,2020,2019-11-01,True,1
4,240.0,32.0,87.0,0.368,11.0,32.0,0.344,20.0,25.0,0.800,...,30.1,145.0,98.0,IND,102,1,2020,2019-11-01,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17647,240.0,39.0,85.0,0.459,12.0,33.0,0.364,25.0,33.0,0.758,...,30.2,161.0,120.0,MIN,108,1,2026,2026-05-08,True,2
17648,240.0,43.0,74.0,0.581,12.0,32.0,0.375,18.0,28.0,0.643,...,40.1,170.0,130.0,DET,109,0,2026,2026-05-09,True,2
17649,240.0,53.0,94.0,0.564,17.0,38.0,0.447,8.0,10.0,0.800,...,34.9,184.0,147.0,LAL,108,1,2026,2026-05-09,True,2
17650,240.0,38.0,81.0,0.469,14.0,30.0,0.467,18.0,25.0,0.720,...,33.6,276.0,127.0,OKC,131,0,2026,2026-05-09,False,2
17651,240.0,41.0,91.0,0.451,9.0,25.0,0.360,18.0,22.0,0.818,...,37.7,147.0,123.0,CLE,116,1,2026,2026-05-09,False,2

In [171]:
df["won"].value_counts()
df["target"].value_counts()

target
0    8813
1    8809
2      30
Name: count, dtype: int64

In [172]:
# Tells us whether NULL value exists in a specific column of the table
nulls = pd.isnull(df)
# Find the count of True(the null value) in the nulls table
nulls = nulls.sum()
nulls = nulls[nulls > 0]
# Columns that don't have NULL value
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [173]:
nulls

gmsc            17652
+/-             17652
mp_max          17652
mp_max.1        17652
gmsc_opp        17652
+/-_opp         17652
mp_max_opp      17652
mp_max_opp.1    17652
dtype: int64

In [174]:
df.columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='str', length=152)

In [175]:
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='str', length=144)

In [176]:
df = df[valid_columns].copy()

In [177]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,41.0,99.0,0.414,12.0,48.0,0.250,22.0,27.0,0.815,...,30.6,182.0,116.0,BRK,123,1,2020,2019-11-01,False,0
1,265.0,40.0,102.0,0.392,14.0,36.0,0.389,16.0,23.0,0.696,...,34.1,206.0,113.0,LAL,119,0,2020,2019-11-01,False,1
2,240.0,44.0,93.0,0.473,13.0,35.0,0.371,26.0,30.0,0.867,...,41.0,246.0,138.0,GSW,110,1,2020,2019-11-01,True,0
3,240.0,39.0,96.0,0.406,5.0,27.0,0.185,19.0,21.0,0.905,...,28.6,123.0,106.0,CLE,95,0,2020,2019-11-01,True,1
4,240.0,32.0,87.0,0.368,11.0,32.0,0.344,20.0,25.0,0.800,...,30.1,145.0,98.0,IND,102,1,2020,2019-11-01,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17647,240.0,39.0,85.0,0.459,12.0,33.0,0.364,25.0,33.0,0.758,...,30.2,161.0,120.0,MIN,108,1,2026,2026-05-08,True,2
17648,240.0,43.0,74.0,0.581,12.0,32.0,0.375,18.0,28.0,0.643,...,40.1,170.0,130.0,DET,109,0,2026,2026-05-09,True,2
17649,240.0,53.0,94.0,0.564,17.0,38.0,0.447,8.0,10.0,0.800,...,34.9,184.0,147.0,LAL,108,1,2026,2026-05-09,True,2
17650,240.0,38.0,81.0,0.469,14.0,30.0,0.467,18.0,25.0,0.720,...,33.6,276.0,127.0,OKC,131,0,2026,2026-05-09,False,2
17651,240.0,41.0,91.0,0.451,9.0,25.0,0.360,18.0,22.0,0.818,...,37.7,147.0,123.0,CLE,116,1,2026,2026-05-09,False,2

In [217]:
#Use Cross Validation to Predict Data
from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import RidgeClassifier

# Machine Learning Model
rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)

# Features == Columns
# direction: contains forward and backward, forward starts with zero features 
#            then picks feature that imporve accuracy the most and continue 
#            doing so until it chooses 30
sfs = SequentialFeatureSelector(rr, n_features_to_select = 30, direction = "forward", cv = split)

removed_columns = ["season", "date", "won", "target", "team", "team_opp"]

selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [179]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
# Converts every data so it falls in between the range of 0 and 1 
# to improve the performance of ridge regression
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [180]:
# Selects the 30 best feature to help predict "target"
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [181]:
# sfs.get_support() method returns true for values/columns selected as 30 best
# columns to predict targetl; It will basically return the name of 30 columns
# selected
predictors = list(selected_columns[sfs.get_support()])

In [182]:
predictors

['mp',
 'fta',
 'stl',
 'ftr',
 'usg%',
 'ortg',
 'fg%_max',
 'ft%_max',
 'pts_max',
 '+/-_max',
 'ts%_max',
 'orb%_max',
 'drb%_max',
 'usg%_max',
 'mp_opp',
 'ft%_opp',
 '3par_opp',
 'usg%_opp',
 'drtg_opp',
 'fga_max_opp',
 '3pa_max_opp',
 'ft_max_opp',
 'orb_max_opp',
 'stl_max_opp',
 'gmsc_max_opp',
 'orb%_max_opp',
 'trb%_max_opp',
 'ast%_max_opp',
 'stl%_max_opp',
 'usg%_max_opp']

In [183]:
# The function will split the data by season so we can take the data of past
# seasons and predict the future seasons
# Start = 2 defines that it needs data of the previous two seasons to make #         predictions
# Step = 1 defines that it will predict data of one season with data of two #
#          season
def backtest(data, model, predictors, start = 2, step = 1):
    all_predictions = []
    
    seasons = sorted(data["season"].unique())
    
    for i in range(start, len(seasons), step):
        season = seasons[i]
        
        # Training Session will take seasons of the past two seasons
        train = data[data["season"] < season]
        # Test Session will take the current season
        test = data[data["season"] == season]
        
        # Takes training datas and decides what predictors/columns affect the 
        # result of data trying to be predicted, target
        model.fit(train[predictors], train["target"])
        
        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index = test.index)
        
        combined = pd.concat([test["target"], preds], axis = 1)
        combined.columns = ['actual', 'prediction']
        
        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [184]:
predictions = backtest(df, rr, predictors)

In [185]:
predictions

       actual  prediction
4492        0           0
4493        1           1
4494        0           1
4495        1           1
4496        1           0
...       ...         ...
17647       2           1
17648       2           1
17649       2           1
17650       2           0
17651       2           1

[13160 rows x 2 columns]

In [186]:
from sklearn.metrics import accuracy_score

predictions = predictions[predictions["actual"] != 2] 
accuracy_score(predictions["actual"], predictions["prediction"])

0.5529322162985529

In [187]:
df.groupby("home").apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])

home
0.0    0.446862
1.0    0.553138
dtype: float64

In [188]:
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

In [189]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,team,season
0,0.000000,0.454545,0.610169,0.345238,0.370370,0.690909,0.294309,0.468085,0.457627,0.735714,...,0.078,1.000000,0.110256,0.404040,0.400000,0.518182,1.0,False,HOU,2020
1,0.333333,0.431818,0.661017,0.292857,0.444444,0.472727,0.520325,0.340426,0.389831,0.565714,...,0.090,0.315514,0.155128,0.525253,0.366667,0.481818,0.0,False,DAL,2020
2,0.000000,0.522727,0.508475,0.485714,0.407407,0.454545,0.491057,0.553191,0.508475,0.810000,...,0.043,0.401468,0.243590,0.727273,0.644444,0.400000,1.0,True,SAS,2020
3,0.000000,0.409091,0.559322,0.326190,0.111111,0.309091,0.188618,0.404255,0.355932,0.864286,...,0.026,0.486373,0.084615,0.106061,0.288889,0.263636,0.0,True,IND,2020
4,0.000000,0.250000,0.406780,0.235714,0.333333,0.400000,0.447154,0.425532,0.423729,0.714286,...,0.140,0.219078,0.103846,0.217172,0.200000,0.327273,1.0,False,CLE,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17647,0.000000,0.409091,0.372881,0.452381,0.370370,0.418182,0.479675,0.531915,0.559322,0.654286,...,0.089,0.475891,0.105128,0.297980,0.444444,0.381818,1.0,True,SAS,2026
17648,0.000000,0.500000,0.186441,0.742857,0.370370,0.400000,0.497561,0.382979,0.474576,0.490000,...,0.287,0.216981,0.232051,0.343434,0.555556,0.390909,0.0,True,CLE,2026
17649,0.000000,0.727273,0.525424,0.702381,0.555556,0.509091,0.614634,0.170213,0.169492,0.714286,...,0.036,0.650943,0.165385,0.414141,0.744444,0.381818,1.0,True,OKC,2026
17650,0.000000,0.386364,0.305085,0.476190,0.444444,0.363636,0.647154,0.382979,0.423729,0.600000,...,0.056,0.475891,0.148718,0.878788,0.522222,0.590909,0.0,False,LAL,2026
17651,0.000000,0.454545,0.474576,0.433333,0.259259,0.272727,0.473171,0.382979,0.372881,0.740000,...,0.065,0.475891,0.201282,0.227273,0.477778,0.454545,1.0,False,DET,2026

In [190]:
def find_team_averages(team):
    # Pandas method that groups rows, in this case, the last 10 
    rolling = team.rolling(10).mean()
    return rolling

df_rolling = df_rolling.groupby(["team", "season"], group_keys = False).apply(find_team_averages)

In [191]:
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17647,0.000000,0.479545,0.410169,0.510714,0.407407,0.436364,0.511057,0.419149,0.423729,0.699286,...,0.272664,0.0575,0.1206,0.338365,0.241282,0.317677,0.521111,0.359091,0.3,0.7
17648,0.033333,0.409091,0.332203,0.489048,0.392593,0.500000,0.440325,0.406383,0.438983,0.633857,...,0.284346,0.0606,0.0982,0.300210,0.149231,0.373232,0.477778,0.398182,0.5,0.5
17649,0.000000,0.534091,0.447458,0.551190,0.466667,0.518182,0.511870,0.334043,0.325424,0.697857,...,0.477570,0.0877,0.0797,0.547065,0.220256,0.640909,0.577778,0.399091,0.5,0.8
17650,0.033333,0.384091,0.276271,0.502143,0.329630,0.320000,0.528293,0.374468,0.396610,0.652571,...,0.271612,0.0911,0.0749,0.371279,0.141667,0.414141,0.453333,0.366364,0.5,0.5
17651,0.000000,0.356818,0.328814,0.420238,0.300000,0.340000,0.458211,0.444681,0.464407,0.659857,...,0.286098,0.0656,0.0993,0.462893,0.150385,0.452020,0.445556,0.307273,0.4,0.6

In [197]:
rolling_cols = [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols
# axis = 1, comnbines two data frams by column 
# (makes the table longer instead of taller(axis = 0))
df = pd.concat([df, df_rolling], axis = 1)
# Drops any rows that have NA values
df = df.dropna()

In [198]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,ast%_max_opp_10_10,stl%_max_opp_10_10,blk%_max_opp_10_10,tov%_max_opp_10_10,usg%_max_opp_10_10,ortg_max_opp_10_10,drtg_max_opp_10_10,total_opp_10_10,home_opp_10_10,won_10_10
228,0.0,0.363636,0.474576,0.328571,0.185185,0.272727,0.343089,0.404255,0.389831,0.751429,...,0.369042,0.0450,0.1144,0.479560,0.166923,0.372222,0.372222,0.455455,0.5,0.1
243,0.0,0.454545,0.440678,0.457143,0.444444,0.509091,0.486179,0.340426,0.322034,0.774286,...,0.303037,0.0458,0.0860,0.407966,0.209744,0.531818,0.407778,0.482727,0.4,0.5
244,0.0,0.522727,0.559322,0.450000,0.222222,0.254545,0.429268,0.297872,0.271186,0.821429,...,0.382944,0.0491,0.0812,0.392348,0.153462,0.443434,0.446667,0.453636,0.5,0.2
254,0.0,0.590909,0.627119,0.478571,0.555556,0.636364,0.502439,0.446809,0.440678,0.725714,...,0.345678,0.0429,0.1063,0.510063,0.230128,0.312626,0.453333,0.383636,0.6,0.8
257,0.0,0.522727,0.644068,0.397619,0.444444,0.418182,0.577236,0.276596,0.288136,0.664286,...,0.337500,0.0431,0.0927,0.353669,0.130769,0.272222,0.407778,0.318182,0.4,0.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17647,0.0,0.409091,0.372881,0.452381,0.370370,0.418182,0.479675,0.531915,0.559322,0.654286,...,0.272664,0.0575,0.1206,0.338365,0.241282,0.317677,0.521111,0.359091,0.3,0.7
17648,0.0,0.500000,0.186441,0.742857,0.370370,0.400000,0.497561,0.382979,0.474576,0.490000,...,0.284346,0.0606,0.0982,0.300210,0.149231,0.373232,0.477778,0.398182,0.5,0.5
17649,0.0,0.727273,0.525424,0.702381,0.555556,0.509091,0.614634,0.170213,0.169492,0.714286,...,0.477570,0.0877,0.0797,0.547065,0.220256,0.640909,0.577778,0.399091,0.5,0.8
17650,0.0,0.386364,0.305085,0.476190,0.444444,0.363636,0.647154,0.382979,0.423729,0.600000,...,0.271612,0.0911,0.0749,0.371279,0.141667,0.414141,0.453333,0.366364,0.5,0.5
17651,0.0,0.454545,0.474576,0.433333,0.259259,0.272727,0.473171,0.382979,0.372881,0.740000,...,0.286098,0.0656,0.0993,0.462893,0.150385,0.452020,0.445556,0.307273,0.4,0.6

In [199]:
# Finds whether the next game for a certain team will be played in home or not;
# Just like what we did with target(taking next row's info and putting it to 
# the end of previous row)
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col

def add_col(df, col_name):
    return df.groupby("team", group_keys = False).apply(lambda x: shift_col(x, col_name))

df["home_next"] = add_col(df, "home")
df["team_opp_next"] = add_col(df, "team_opp")
df["date_next"] = add_col(df, "date")

/var/folders/yq/k72_3tsd4dv_nt6nq1zwz2g80000gn/T/ipykernel_13253/4087447646.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["home_next"] = add_col(df, "home")
/var/folders/yq/k72_3tsd4dv_nt6nq1zwz2g80000gn/T/ipykernel_13253/4087447646.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["team_opp_next"] = add_col(df, "team_opp")
/var/folders/yq/k72_3tsd4dv_nt6nq1zwz2g80000gn/T/ipykernel_13253/4087447646.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["date_next"] = add_col(df, "date")

In [200]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp_10_10,usg%_max_opp_10_10,ortg_max_opp_10_10,drtg_max_opp_10_10,total_opp_10_10,home_opp_10_10,won_10_10,home_next,team_opp_next,date_next
228,0.0,0.363636,0.474576,0.328571,0.185185,0.272727,0.343089,0.404255,0.389831,0.751429,...,0.479560,0.166923,0.372222,0.372222,0.455455,0.5,0.1,0.0,MEM,2019-11-19
243,0.0,0.454545,0.440678,0.457143,0.444444,0.509091,0.486179,0.340426,0.322034,0.774286,...,0.407966,0.209744,0.531818,0.407778,0.482727,0.4,0.5,1.0,UTA,2019-11-20
244,0.0,0.522727,0.559322,0.450000,0.222222,0.254545,0.429268,0.297872,0.271186,0.821429,...,0.392348,0.153462,0.443434,0.446667,0.453636,0.5,0.2,0.0,WAS,2019-11-20
254,0.0,0.590909,0.627119,0.478571,0.555556,0.636364,0.502439,0.446809,0.440678,0.725714,...,0.510063,0.230128,0.312626,0.453333,0.383636,0.6,0.8,0.0,DEN,2019-11-20
257,0.0,0.522727,0.644068,0.397619,0.444444,0.418182,0.577236,0.276596,0.288136,0.664286,...,0.353669,0.130769,0.272222,0.407778,0.318182,0.4,0.7,1.0,ORL,2019-11-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17647,0.0,0.409091,0.372881,0.452381,0.370370,0.418182,0.479675,0.531915,0.559322,0.654286,...,0.338365,0.241282,0.317677,0.521111,0.359091,0.3,0.7,NaN,NaN,NaN
17648,0.0,0.500000,0.186441,0.742857,0.370370,0.400000,0.497561,0.382979,0.474576,0.490000,...,0.300210,0.149231,0.373232,0.477778,0.398182,0.5,0.5,NaN,NaN,NaN
17649,0.0,0.727273,0.525424,0.702381,0.555556,0.509091,0.614634,0.170213,0.169492,0.714286,...,0.547065,0.220256,0.640909,0.577778,0.399091,0.5,0.8,NaN,NaN,NaN
17650,0.0,0.386364,0.305085,0.476190,0.444444,0.363636,0.647154,0.382979,0.423729,0.600000,...,0.371279,0.141667,0.414141,0.453333,0.366364,0.5,0.5,NaN,NaN,NaN
17651,0.0,0.454545,0.474576,0.433333,0.259259,0.272727,0.473171,0.382979,0.372881,0.740000,...,0.462893,0.150385,0.452020,0.445556,0.307273,0.4,0.6,NaN,NaN,NaN

In [209]:
# Works like inner join in SQL
full = df.merge(
                df[rolling_cols + ["team_opp_next", "date_next", "team"]], 
                left_on = ["team", "date_next"], 
                right_on = ["team_opp_next", "date_next"]
)
full.columns = full.columns.str.replace("_10_10", "_10", regex=True)

In [214]:
full

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,blk%_max_opp_10_y,tov%_max_opp_10_y,usg%_max_opp_10_y,ortg_max_opp_10_y,drtg_max_opp_10_y,total_opp_10_y,home_opp_10_y,won_10_y,team_opp_next_y,team_y
0,0.0,0.522727,0.644068,0.397619,0.444444,0.418182,0.577236,0.276596,0.288136,0.664286,...,0.0941,0.288784,0.165000,0.398990,0.393333,0.361818,0.3,0.4,IND,ORL
1,0.0,0.431818,0.491525,0.395238,0.518519,0.345455,0.785366,0.170213,0.220339,0.450000,...,0.0751,0.310901,0.125641,0.307071,0.440000,0.376364,0.8,0.9,POR,MIL
2,0.0,0.340909,0.423729,0.333333,0.259259,0.272727,0.473171,0.297872,0.322034,0.624286,...,0.0714,0.367191,0.118590,0.395960,0.455556,0.347273,0.4,0.9,MEM,LAL
3,0.0,0.409091,0.440678,0.402381,0.407407,0.400000,0.547967,0.382979,0.440678,0.560000,...,0.0828,0.375996,0.141282,0.415657,0.438889,0.479091,0.5,0.1,PHI,SAS
4,0.0,0.318182,0.474576,0.276190,0.259259,0.400000,0.344715,0.382979,0.474576,0.490000,...,0.0927,0.353669,0.130769,0.272222,0.407778,0.318182,0.4,0.7,ORL,IND
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15645,0.0,0.295455,0.203390,0.438095,0.407407,0.436364,0.508943,0.446809,0.474576,0.642857,...,0.0768,0.417505,0.190769,0.454040,0.550000,0.315455,0.3,0.7,PHI,NYK
15646,0.0,0.409091,0.288136,0.521429,0.444444,0.327273,0.700813,0.319149,0.338983,0.642857,...,0.0725,0.294864,0.130513,0.372222,0.487778,0.405455,0.5,0.5,DET,CLE
15647,0.0,0.295455,0.305085,0.359524,0.185185,0.400000,0.243902,0.468085,0.457627,0.735714,...,0.1107,0.436059,0.143462,0.445960,0.465556,0.311818,0.4,0.7,CLE,DET
15648,0.0,0.409091,0.254237,0.550000,0.333333,0.345455,0.504065,0.382979,0.355932,0.795714,...,0.0811,0.512055,0.217564,0.628283,0.567778,0.380000,0.5,0.8,LAL,OKC
15649,0.0,0.545455,0.305085,0.683333,0.444444,0.472727,0.520325,0.446809,0.440678,0.725714,...,0.0741,0.366562,0.148590,0.345960,0.446667,0.313636,0.5,0.6,OKC,LAL

In [211]:
full[["team_x", "team_opp_next_x", "team_y", "team_opp_next_y", "date_next"]]

      team_x team_opp_next_x team_y team_opp_next_y   date_next
0        IND             ORL    ORL             IND  2019-11-23
1        POR             MIL    MIL             POR  2019-11-21
2        MEM             LAL    LAL             MEM  2019-11-23
3        PHI             SAS    SAS             PHI  2019-11-22
4        ORL             IND    IND             ORL  2019-11-23
...      ...             ...    ...             ...         ...
15645    PHI             NYK    NYK             PHI  2026-05-08
15646    DET             CLE    CLE             DET  2026-05-09
15647    CLE             DET    DET             CLE  2026-05-09
15648    LAL             OKC    OKC             LAL  2026-05-09
15649    OKC             LAL    LAL             OKC  2026-05-09

[15650 rows x 5 columns]

In [224]:
# Not selecting all the columns with the object data type 
removed_columns = list(
                        full.columns[
                                        (full.dtypes == "object") | 
                                        (full.dtypes == "str")
                        ]
                    ) + removed_columns

In [220]:
print(full[["team_opp_next_y", "team_y"]].dtypes)

team_opp_next_y    str
team_y             str
dtype: object

In [227]:
removed_columns = list(set(removed_columns))
removed_columns

['target',
 'season',
 'team',
 'team_opp_next_x',
 'team_opp',
 'team_y',
 'team_x',
 'won',
 'date',
 'date_next',
 'team_opp_next_y']

In [229]:
selected_columns = full.columns[~full.columns.isin(removed_columns)]

In [230]:
sfs.fit(full[selected_columns], full["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [231]:
predictors = list(selected_columns[sfs.get_support()])

In [232]:
predictors

['fta',
 'orb%',
 'tov%',
 'usg%',
 'efg%_max',
 'ast%_max',
 'stl%_max',
 '3pa_opp',
 'tov_opp',
 'drb%_opp',
 'usg%_opp',
 'orb_max_opp',
 'pts_max_opp',
 '3par_max_opp',
 'usg%_10',
 'gmsc_max_10',
 '+/-_max_10',
 'ft%_opp_10',
 'usg%_opp_10',
 'ft%_max_opp_10',
 'usg%_10_x',
 'ft%_opp_10_x',
 'usg%_opp_10_x',
 'home_next',
 'usg%_10_y',
 'stl_max_10_y',
 'pts_max_10_y',
 '+/-_max_10_y',
 'ast%_opp_10_y',
 'usg%_opp_10_y']

In [233]:
predictions = backtest(full, rr, predictors)
accuracy_score(predictions["actual"], predictions["prediction"])

0.6329016868291021